name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: [ 3.1, 5.0 ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install dependencies
      run: dotnet restore
    # Debug and Release mighht be different due to conditional compilation, so validate both.
    - name: Build (Debug)
      run: dotnet build --configuration Debug --no-restore
    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    # Not safe to test Debug build as it runs tests in parallel, occasional triggering a bug in the test adapter.

